### ISSUE TITLE
Error : Unable to detect graphics environment

### ISSUE THREAD

**Issue by melamm** [psharkey/docker#66]
I tried to run the images and I have the error : 
$ sudo docker run psharkey/intellij

**Startup Error: Unable to detect graphics environment**

**Comment by smartcai** [comment]
> I tried to run the images and I have the error :
> $ sudo docker run psharkey/intellij
> 
> **Startup Error: Unable to detect graphics environment**

docker run psharkey/intellij   You can have a try
